config/routes.rb
RailsApp::Application.routes.draw do

  if Rails.env == 'development'
    get "/app/:action", controller: "application"
  end

  get '/news' => 'news#index', as: "news"

  get '/404' => 'application#render_404'
  get "/rel" => 'application#reload_settings'
  root :to => 'posts#index'

  devise_scope :user do
    get "/users/glogout" => 'users/sessions#destroy', as: "destroy_user_session_get"
    get '/users/show/:id' => 'users/registrations#show', as: 'show_user_registration'
    get '/users/list' => 'users/registrations#list', as: 'list_user_registrations'
  end

  controller "users/messages" do
    get "/messages/inbox", action: "inbox"
    get "/messages/outbox", action: "outbox"
    get "/messages/deleted", action: "deleted"
    get "/messages/write", action: "write"
    get "/messages/:id", action: "read", as: "message"
    post "/messages/send", action: "send_message"
    get "/messages/:id/delete", action: "delete", as: "message_delete"
    get '/messages/:id/perm_delete', action: "permanent_delete", as: "message_delete_permanent"
  end

  resources :posts

  controller "posts" do
    get "/user/:user_id/posts", action: "user_posts", as: "user_posts"
    get "/bookmarks", action: "bookmarks", as: "bookmarks"
    get "/posts/:id/from-bookmarks", action: "destroy_bookmark", as: "post_unbookmark"
    get "/posts/:id/to-bookmarks", action: "create_bookmark", as: "post_bookmark"
    post "/posts/:id/comment", action: "comment", as: "comment_post"
    post "/posts/:id/vote/up", action: "vote", as: 'vote_post_up'
    post "/posts/:id/vote/down", action: "vote", as: 'vote_post_down', minus: true
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users,
    :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks', :sessions => 'users/sessions' },
    :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => 'register' }

  if Rails.env == 'production'
    match '/:something', :to => "application#render_404", :constraints => { :something => /.*/ }
  end

end

app/views/shared/404.html.haml
%h1 Ой! Сторінка не знайдена :(

app/views/shared/_chrome-frame.html.haml
/[if lt IE 7]
  <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
/ Add your site or application content here

app/views/shared/_head.html.haml
#head
  = link_to root_path, id: 'logo' do
    = image_tag "logo-v2.png"
  %ul#nav
    %li{class: ('current' if current_page?(posts_path) || current_page?(root_path))}
      = link_to t('common.posts'), posts_path

    -if user_signed_in?
      %li{class: ("current" if current_page?(new_post_path))}
        = link_to t("common.new_post"), new_post_path

    %li{class: ("current" if current_page?(list_user_registrations_path))}
      = link_to t('common.authors'), list_user_registrations_path
    - unless user_signed_in?
      %li{class: ("current" if current_page?(new_user_session_path))}
        = link_to t('common.login'), new_user_session_path
      %li{class: ("current" if current_page?(new_user_registration_path))}
        = link_to t('common.registration'), new_user_registration_path
  - if user_signed_in?
    #user
      %a{href: "javascript:void(0);", :"data-dropdown" => "#user-dropdown"}
        = image_tag current_user.avatar
      #user-dropdown.dropdown.dropdown-tip
        %ul.dropdown-menu
          %li
            = link_to t('common.profile'), show_user_registration_path(current_user)
          %li
            = link_to t('common.my_posts'), user_posts_path(current_user)
          %li 
            = link_to t('common.inbox'), messages_inbox_path
          %li 
            = link_to t('common.bookmarks'), bookmarks_path
          %li 
            = link_to t('common.logout'), destroy_user_session_path, method: :delete
  -# #search-btn
    = image_tag "icons/search.png"

app/views/shared/_javascripts.html.haml
= javascript_include_tag "application.js"
= yield :activerecord_js_messages
= yield :view_js
- if flash[:notice]
  :javascript
    noty(#{ raw({text: flash[:notice], type: "alert", timeout: 1000}.to_json) })
- if flash[:alert]
  :javascript
    noty(#{ raw({text: flash[:alert], type: "warning"}.to_json) })
- if flash[:error]
  :javascript
    noty(#{ raw({text: flash[:error], type: "error"}.to_json) })

app/views/shared/_js_notifications.html.erb
<script language="javascript" type="text/javascript">
  jQuery(document).ready(function(){
    <% js_notifications.each do |notification| %> 
      noty(<%= raw notification %>);
    <% end %>
  });
</script>

app/views/shared/_nojs_nav.html.haml
%noscript
  #nojs_nav
    %ul
      - if user_signed_in?
        %li
          = link_to t('common.my_profile'), show_user_registration_path(current_user)
        %li
          = link_to t('common.bookmarks'), bookmarks_path
        %li
          = link_to t('common.my_messages'), messages_inbox_path
        %li
          = link_to t('common.logout'), destroy_user_session_get_path
        -# %li
          %form
            %input{type: "text", placeholder: "Пошук"}
            %input{type: "submit", value: "Ok"}
  .flash-messages
    - if flash[:notice] || flash[:alert] || flash[:error]
      .messages
        Повідомлення:
      .flash-notice=flash[:notice]
      .flash-alert=flash[:alert]
      .flash-error=flash[:error]

app/views/shared/_nojs_notifications.html.erb
<noscript>
  <%= t('common.there_were_errors') %>
  <ul class="activerecord_errors">
    <% nojs_notifications.each do |notification| %>
      <li>
        <%= notification %>
      </li>
    <% end %>
  </ul>
</noscript>