config/routes.rb
RailsApp::Application.routes.draw do

  if Rails.env == 'development'
    get "/app/:action", controller: "application"
  end

  get '/news' => 'news#index', as: "news"

  get '/404' => 'application#render_404'
  get "/rel" => 'application#reload_settings'
  root :to => 'posts#index'

  devise_scope :user do
    get "/users/glogout" => 'users/sessions#destroy', as: "destroy_user_session_get"
    get '/users/show/:id' => 'users/registrations#show', as: 'show_user_registration'
    get '/users/list' => 'users/registrations#list', as: 'list_user_registrations'
  end

  controller "users/messages" do
    get "/messages/inbox", action: "inbox"
    get "/messages/outbox", action: "outbox"
    get "/messages/deleted", action: "deleted"
    get "/messages/write", action: "write"
    get "/messages/:id", action: "read", as: "message"
    post "/messages/send", action: "send_message"
    get "/messages/:id/delete", action: "delete", as: "message_delete"
    get '/messages/:id/perm_delete', action: "permanent_delete", as: "message_delete_permanent"
  end

  resources :posts

  controller "posts" do
    get "/user/:user_id/posts", action: "user_posts", as: "user_posts"
    get "/bookmarks", action: "bookmarks", as: "bookmarks"
    get "/posts/:id/from-bookmarks", action: "destroy_bookmark", as: "post_unbookmark"
    get "/posts/:id/to-bookmarks", action: "create_bookmark", as: "post_bookmark"
    post "/posts/:id/comment", action: "comment", as: "comment_post"
    post "/posts/:id/vote/up", action: "vote", as: 'vote_post_up'
    post "/posts/:id/vote/down", action: "vote", as: 'vote_post_down', minus: true
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users,
    :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks', :sessions => 'users/sessions' },
    :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => 'register' }

  if Rails.env == 'production'
    match '/:something', :to => "application#render_404", :constraints => { :something => /.*/ }
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise  :database_authenticatable, 
          :timeoutable, 
          :registerable,
          :recoverable,
          :omniauthable,
          :omniauth_providers => [:vkontakte, :facebook, :twitter]

  acts_as_messageable required: [:body]
  self.authentication_keys = [:login]

  # Associations
  has_many :posts
  has_many :ratings
  has_many :bookmarks
  has_many :providers

  # Validations
  validates :nickname,
            presence: true,
            uniqueness: true, length: { in: 3..11 }

  validates_presence_of :email, presence: true
  validates_format_of :email, with: /.+@(\w+\.)+\w+/

  validates :password, 
            presence: true, 
            length: { minimum: Rails.env == 'development' ? 1 : 4 }, 
            confirmation: true

  validates :password_confirmation, :fullname,
            presence: true

  validates_attachment :avatar,
    :content_type => { :content_type => ['image/jpg', 'image/jpeg', 'image/png'] }

  # Attributes

  has_attached_file :avatar,
    :styles => { :default => ['84x84#'] },
    :url => ':hash_data/:filename.:extenstion',
    :default_url => "default-avatar.png"

  attr_accessible :nickname, :fullname, :password, 
                  :password_confirmation, :avatar,
                  :email

  attr_accessor :login

  # Class methods

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(nickname) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def self.sort(opts={})
    opts[:rating] ? self.order('rating DESC') : self
  end

  # Instance Methods

  def posts_bookmarks
    posts_ids = bookmarks.map(&:post_id)
    Post.find(posts_ids)
  end

  def has_in_bookmarks?(post_id)
    !!self.bookmarks.find_by_post_id(post_id)
  end

  def voting_level
    Level.new(posts_rating_sum).to_s.to_i
  end
  alias :level :voting_level

  def posts_rating_sum
    self.posts.sum :rating
  end

  def voted?(post_id)
    !!ratings.find_by_post_id(post_id)
  end

  def is_author_of?(post)
    post.user && self.id == post.user.id
  end

  def vk?
    self.provider == 'vkontakte'
  end

  def admin?
    self.role == 'admin'
  end

end

app/models/user/level.rb
class User
  class Level
    RANGES = {
      1 => (0...50),
      2 => (50...100),
      3 => (100...200),
      4 => (200...500),
      5 => (500...99999999999)
    }
    def initialize(rating_sum)
      @level = detect_level(rating_sum)
    end

    def to_s
      @level
    end

    def to_i
      self.to_s.to_i
    end

    private

    def detect_level(rating_sum)
      level = RANGES.detect { |level, range| range.include?(rating_sum) }
      if level.nil?
        rating_sum > 500 ? 5 : 1
      else
        level[0]
      end
    end
  end
end

app/models/user/provider.rb
class User::Provider < ActiveRecord::Base
  belongs_to :user
  attr_accessible :provider, :uid, :user_id
  validates_uniqueness_of :provider, scope: :user_id
end

app/controllers/users/messages_controller.rb
class Users::MessagesController < ApplicationController
  before_filter :authenticate_user!

  #With views
  def inbox
    @messages = current_user.received_messages
  end

  def outbox
    @messages = current_user.sent_messages
  end

  def deleted
    @messages = current_user.deleted_messages
  end

  def write
  end

  def read
    @message = current_user.messages.find(params[:id])
    render_404 unless @message
  end

  #Without views
  def send_message
    recipient_nicknames = separate_by_comma params[:recipients]
    recipients = User.
      find_all_by_nickname(recipient_nicknames)

    recipients.each do |recipient|
      msg = current_user.send_message(recipient, params[:body] )
    end
    flash[:alert] = t('common.messages.need_any_recipient') if recipients.empty?
    redirect_to :back
  end

  def delete
    message = current_user.messages.find(params[:id])
    current_user.delete_message(message)
    redirect_to :back
  end

  def permanent_delete
    message = current_user.deleted_messages.find(params[:id])
    current_user.delete_message(message)
    redirect_to :back
  end

  private
  def separate_by_comma(string)
    string.
      split(',').
      map{|i|i.strip}
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    strategy!
  end

  def twitter
    strategy!
  end

  def vkontakte
    strategy!
  end

  private

  def strategy!
    auth = request.env['omniauth.auth']
    provider = User::Provider.find_by_provider_and_uid(auth.provider, auth.uid)
    
    if !provider && !user_signed_in?
      return redirect_to new_user_session_path(login_for_omniauth: true, provider: auth.provider)
    elsif user_signed_in?
      session['devise.social_data'] = nil;
      provider = current_user.
                  providers.
                  find_or_create_by_provider_and_uid provider: auth.provider, uid: auth.uid
    end

    set_flash_message(:notice, :success) if is_navigational_format?
    sign_in_and_redirect provider.user, event: :authentication
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    build_resource

    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_up(resource_name, resource)

        respond_to do |f|
          f.html { redirect_to after_sign_up_path_for(resource) }
          f.json { render json: { status: true, message: t('devise.registrations.signed_up') } }
        end
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      # respond_with resource
      respond_to do |f|
        f.html { render resource }
        f.json { render json: { status: false, errors: resource.errors.full_messages } }
      end
    end
  end
  
  def show
    @user = User.find(params[:id])
  end

  def list
    @users = User.sort(rating: true)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message(:notice, :signed_in) if is_navigational_format?
    sign_in(resource_name, resource)

    respond_to do |f|
      f.html {
        if params[:login_for_omniauth] && params[:provider]
          redirect_to user_omniauth_authorize_path(params[:provider])
        else
          redirect_to after_sign_in_path_for(resource)
        end
      }
    end
  end
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
  def ukr_count(number, opts={})
    number = number.to_i
    return false if number < 1
    number = number.to_s[/\d\d$/].to_i if number > 100
    case number
      when 1
        return opts[:first] || :first
      when 2,3,4
        return opts[:second] || :second
      else
        return opts[:else] || :else
    end
  end
end

app/views/users/messages/_links.html.haml
:css
  #page #content h2 a {
    font-weight: normal;
  }
.links
  %h2= link_to t('common.write'), messages_write_path
  %h2= link_to t('common.incoming'), messages_inbox_path
  %h2= link_to t('common.outcoming'), messages_outbox_path
  %h2= link_to t('common.deleted'), messages_deleted_path

app/views/users/messages/_message.html.haml
.message
  .content
    .text=message.body
    %h4 #{message.sent_messageable.nickname}, #{message.created_at.strftime("%Y/%m/%d %H:%M:%S")}
    %a.reply{href: "javascript:void(0);"} Відповісти

app/views/users/messages/_messages.html.haml
.messages
  %div
    - case params[:action]
      - when "inbox"
        Вхідні повідомлення:
      - when "outbox"
        Вихідні повідомлення:
      - when "deleted"
        Видалені повідомлення:
    %br/
    - if messages && messages.any?
      %ul
        - messages.each do |msg|
          %li
            = msg.body
            %br/
            - case params[:action]
              - when 'deleted'
                = link_to t('common.delete'), message_delete_permanent_path(msg)
              - else
                = link_to t('common.delete'), message_delete_path(msg)
            %br/
            - case params[:action]
              - when 'inbox'
                != t 'common.messages.written', 
                  author: msg.sent_messageable.nickname, 
                  recipient: t('common.messages.meto'),
                  time: msg.created_at.strftime("%Y/%m/%d %H:%I:%M")
              - when 'outbox'
                != t 'common.messages.written',
                  author: t('common.i'),
                  recipient: msg.received_messageable.nickname,
                  time: msg.created_at.strftime("%Y/%m/%d %H:%I:%M")
              - when 'deleted'
                != t 'common.messages.written',
                  author: msg.sent_messageable.nickname,
                  recipient: msg.received_messageable.nickname,
                  time: msg.created_at.strftime("%Y/%m/%d %H:%I:%M")
    - else
      Повідомлень немає :(

app/views/users/messages/deleted.html.haml
.inbox
  = render "links"
  = render partial: "messages", object: @messages

app/views/users/messages/inbox.html.haml
.inbox
  = render "links"
  = render partial: "messages", object: @messages

app/views/users/messages/outbox.html.haml
.inbox
  = render "links"
  = render partial: "messages", object: @messages

app/views/users/messages/read.html.haml
.inbox
  = render "links"
  = render partial: "message", object: @message

app/views/users/messages/write.html.haml
.inbox
  = render 'links'
  = form_tag messages_send_path do
    = text_field_tag :recipients, nil, style: "margin-top:15px;", placeholder: t('common.recipients')
    %br/
    = text_area_tag :body, nil, style: "margin-top: 15px;", cols: 35, rows: 5
    %br/
    = submit_tag t('common.send'), style: "margin-top:15px;"