config/routes.rb
RailsApp::Application.routes.draw do

  if Rails.env == 'development'
    get "/app/:action", controller: "application"
  end

  get '/news' => 'news#index', as: "news"

  get '/404' => 'application#render_404'
  get "/rel" => 'application#reload_settings'
  root :to => 'posts#index'

  devise_scope :user do
    get "/users/glogout" => 'users/sessions#destroy', as: "destroy_user_session_get"
    get '/users/show/:id' => 'users/registrations#show', as: 'show_user_registration'
    get '/users/list' => 'users/registrations#list', as: 'list_user_registrations'
  end

  controller "users/messages" do
    get "/messages/inbox", action: "inbox"
    get "/messages/outbox", action: "outbox"
    get "/messages/deleted", action: "deleted"
    get "/messages/write", action: "write"
    get "/messages/:id", action: "read", as: "message"
    post "/messages/send", action: "send_message"
    get "/messages/:id/delete", action: "delete", as: "message_delete"
    get '/messages/:id/perm_delete', action: "permanent_delete", as: "message_delete_permanent"
  end

  resources :posts

  controller "posts" do
    get "/user/:user_id/posts", action: "user_posts", as: "user_posts"
    get "/bookmarks", action: "bookmarks", as: "bookmarks"
    get "/posts/:id/from-bookmarks", action: "destroy_bookmark", as: "post_unbookmark"
    get "/posts/:id/to-bookmarks", action: "create_bookmark", as: "post_bookmark"
    post "/posts/:id/comment", action: "comment", as: "comment_post"
    post "/posts/:id/vote/up", action: "vote", as: 'vote_post_up'
    post "/posts/:id/vote/down", action: "vote", as: 'vote_post_down', minus: true
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users,
    :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks', :sessions => 'users/sessions' },
    :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => 'register' }

  if Rails.env == 'production'
    match '/:something', :to => "application#render_404", :constraints => { :something => /.*/ }
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

  acts_as_commentable
  self.per_page = SiteConfig.posts.posts_per_page

  GENRES = %w{
    prose
    poetry
  }

  TYPES = %w{ 
    opus 
    news
  }

  # Associations
  belongs_to :user
  has_many :ratings
  before_save :set_user_rating
  has_many :bookmarks

  # Validations
  validates :title, :content, :genre, :presence => true
  validates_inclusion_of :genre, :in => GENRES

  # Attributes
  attr_accessible :annotation, :content, 
                  :title, :genre, :published

  before_validation do |record|
    record.post_type ||= "opus"
  end

  # Scopes
  scope :published, 
        ->{ where(published: true) }
  scope :today, 
        ->{ where(created_at: Time.new.beginning_of_day..Time.new.end_of_day) }
  scope :yesterday, 
        ->{ where(created_at: Time.new.yesterday.beginning_of_day..Time.new.yesterday.end_of_day ) }
  scope :this_week, 
        ->{ where(created_at: Time.new.beginning_of_week..Time.new.end_of_week) }
  scope :genre,
        ->(genre) { where(genre: genre) }
  scope :by_rating,
        ->{ order('rating DESC') }
  scope :recent,
        ->{ order('created_at DESC') }

  # Instance methods
  def genres_for_select
    GENRES.map { |g|
      [ (block_given? ? yield(g) : g.humanize), g ]
    }
  end

  def belongs_to?(user)
    return false unless user
    self.user.id == user.id
  end

  def i18n_genre
    I18n.t("common.#{genre}")
  end

  def vote(vote, user_id)
    ratings.create vote: vote, user_id: user_id
    self.rating = ratings.sum :vote
    save
    return self.rating
  end

  private

  def set_user_rating
    if self.rating_changed?
      self.user.update_attribute :rating, (self.user.posts_rating_sum + self.rating)
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  # Actions with views

  def index
    @posts = Post.
              published.
              recent.
              paginate(:page => params[:page])
  end

  def user_posts
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def bookmarks
    @posts = current_user.posts_bookmarks
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = current_user.posts.build
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  # Actions with json-response

  def vote
    post = Post.find(params[:id])
    if current_user.voted?(params[:id])
      flash[:notice] = t('common.voted_already')
      return redirect_to post
    end
    user_id = current_user.id.to_i
    count = current_user.voting_level.to_i
    count = -count if params[:minus]

    rating = post.vote(count, user_id) 

    if request.xhr?
      render text: { rating: rating }.to_json
    else
      flash[:notice] = t('common.vote_accepted')
      redirect_to post
    end
  end

  def comment
    post = Post.find(params[:id]) 
    body = params[:comment] ? params[:comment][:body] : nil
    Comment.build_from(post, current_user.id, body).save

    if request.xhr?
      render text: { comment: comment.body }.to_json
    else
      redirect_to :back, notice: t('common.comment_writed')
    end
  end

  def create_bookmark
    current_user.
      bookmarks.
      create post_id: params[:id] if params[:id]
    if request.xhr?
      render text: { msg: "Bookmark created" }
    else
      flash[:notice] = t('common.bookmark_created')
      redirect_to :back
    end
  end

  def destroy_bookmark
    current_user.
      bookmarks.
      find_by_post_id(params[:id]).
      destroy
    if request.xhr?
      render text: { msg: "Bookmark destroyed" }
    else
      flash[:notice] = t('common.bookmark_destroyed')
      redirect_to :back
    end
  end

  # Actions without views

  def create
    @post = current_user.
            posts.
            build(params[:post])

    if @post.save
      redirect_to @post, notice: t('common.post_writed')
    else
      flash[:error] = t('common.something_went_wrong')
      render :new
    end
  end

  def update
    @post = current_user.
              posts.
              find(params[:id])

    if @post.update_attributes(params[:post])
      redirect_to @post, notice: t('common.post_edited')
    else
      flash[:error] = t('common.something_went_wrong')
      render :edit
    end
  end

  def destroy
    current_user.posts.find(params[:id]).destroy
    flash[:notice] = t('common.post_destroyed')
    redirect_to posts_path
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper

  def link_to_sorted(name, opts={})
    opts.stringify_keys!
    if_current_state = !!opts.
      find { |k,v| params[:sort] && params[:sort][k] == v }
    html_opts = if_current_state ? 
      { class: 'current' } : {}
    html_opts = opts.delete('html').merge(html_opts) if opts['html']
    url_opts = params[:sort] ? params[:sort].merge(opts) : opts
    link_to name, posts_path(:sort => url_opts), html_opts
  end

  def user_voted?(post)
    user_signed_in? && current_user.voted?(post)
  end

  def rate_up_link(post)
    if !user_voted?(post)
      link_to '+', rate_post_up_path(post), :method => :post, remote: true, class: 'rate_up'
    end
  end

  def rate_down_link(post)
    if !user_voted?(post)
      link_to '-', rate_post_down_path(post), :method => :post, remote: true, class: 'rate_down'
    end
  end

  def one_post_page?
    params[:action] == 'show'
  end
end

app/views/posts/_comments.html.haml
#comments
  %h1=t('common.comments')
  - if post.root_comments.any?
    - post.root_comments.each do |comment|
      .comment
        .info
          %span.author= comment.user.nickname
          %span.created_at= comment.created_at.to_s
        .content= comment.body
  - else
    = t('common.no_comments')
  .clearfix
  - if user_signed_in?
    %hr/
    = form_for :comment, url: comment_post_path(post), method: :post do |f|
      = f.label t('common.your_comment')
      %br/
      = f.text_area :body, rows: 5
      %br/
      = f.submit t('common.send')

app/views/posts/_post.html.haml
-# User section
- if user_signed_in?
  .vote{style: 'display:none;'}
    = link_to "+", vote_post_up_path(post), class: "plus", method: :post
    %hr
    = link_to "-", vote_post_down_path(post), class: "minus", method: :post
.author
  = link_to image_tag(post.user.avatar), show_user_registration_path(post.user)
  = link_to post.user.nickname, show_user_registration_path(post.user), class: 'nickname'
  
  -# Rating under user avatar
  .rating
    %i.icn1.icn-author_rating
    %span.text1= post.user.rating
    %i.icn2.icn-author_posts
    %span.text2= post.user.posts.count

-# Content wrapper
.wrap
  .meta
    %i.icn1.icn-views
    %span.text 0
    %i.icn2.icn-comments
    %span.text= post.comment_threads.count
    %i.icn3.icn-rating
    %span.text= post.rating
    %i.icn4.icn-people_voted
    %span.text 0
    %span.genre= post.i18n_genre
    - if user_signed_in?
      %a.bookmark{href: "javascript:void(0);"}
    %span.date 2013/05/23
  .content
    %h1.header
      = link_to post.title, post_path(post.id)
      - if post.belongs_to?(current_user)
        = link_to '', edit_post_path(post), class: "icn16w-pencil"
      %noscript
        %a{href: "javascript:void(0);"} -
        %a{href: "javascript:void(0);"} +

    -# post content
    .text{class: (one_post_page? ? "opened" : '')}
      = simple_format(post.content)
  - if params[:action] == 'index'
    .more
.clearfix

app/views/posts/bookmarks.html.haml
%h1=t('common.pages.bookmarks')
- if @posts.any?
  - @posts.each do |post|
    .post
      = render partial: "post", object: post
- else
  %p=t('common.i_have_no_bookmarks')

app/views/posts/edit.html.haml
%h1=t('common.pages.edit_post')
= form_for @post, url: post_path(@post), html: { id: 'edit-post' } do |f|
  .info
    = f.label :title
    = f.text_field :title

    = f.label :genre
    = f.select :genre, f.object.genres_for_select { |genre| t("common.#{genre}") }

    = f.check_box :published
    = f.label :published

    = f.submit t('common.send')

  .content
    = f.label :content
    = f.text_area :content

app/views/posts/index.html.haml
%h1.pagetitle=t('common.pages.all_posts')
- if @posts.any?
  - @posts.each do |post|
    .post
      = render partial: "post", object: post
- else
  %p=t('common.no_one_loaded_any_post')

app/views/posts/new.html.haml
%h1=t('common.pages.new_post')
= form_for @post, url: posts_path, html: { id: 'new-post' } do |f|
  .info
    = f.label :title
    = f.text_field :title

    = f.label :genre
    = f.select :genre, f.object.genres_for_select { |genre| t(".#{genre}") }

    = f.check_box :published
    = f.label :published

    = f.submit t('common.send')

  .content
    = f.label :content
    = f.text_area :content

app/views/posts/show.html.haml
#post
  =render partial: 'post', object: @post
=render partial: 'comments', locals: { post: @post }

app/views/posts/user_posts.html.haml
%h1=t('common.my_posts')
- if @posts.any?
  - @posts.each do |post|
    .post
      = render partial: "post", object: post
- else
  %p= t('common.i_not_loaded_any_post')